# This is a basic workflow to help you get started with Actions

name: Delete Azure Deployment

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  issues:
    types: closed
      

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  delete-from-azure:
  
    env:
      WEBAPP_NAME: rerwinx-multicloud-web 
    
    if: startsWith(github.event.issue.title, 'Deploy to Azure') 
    
    runs-on: ubuntu-latest
    
    steps:
    
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
     
      - name: Delete the web app
        env:
          RESOURCE_GROUP: rerwinxmulticloud
        run: az webapp delete --resource-group $RESOURCE_GROUP --name $WEBAPP_NAME
        
      - name: Azure logout
        run: az logout
