name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
   
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    
    # We don't need to build the project.  
    #- name: Build with dotnet
    #  run: dotnet build --configuration Release
   
    - uses: Azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        # password: ${{ secrets.REGISTRY_PASSWORD }}
        # Can I use GitHub Token here?
        
    - name: Build image and push to Packages 
    - run: |
        docker build -t aspnetapp .
        docker tag aspnetapp docker.pkg.github.com/rerwinx/multi-cloud-deploy/aspnetapp:${{ github.sha }}        
        docker push docker.pkg.github.com/rerwinx/multi-cloud-deploy/aspnetapp:${{ github.sha }}
      
